### ISSUE TITLE
Create mermaid diagram with an overview of the projects process

### ISSUE THREAD

**Issue by ctmartinez1992** [runtimerevolution/labs#119]
You can use openai to generate the diagram.

**Comment by sIldefonsoRR** [comment]
Here is an example of a form to create a diagram from mermaid code:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mermaid Diagram Renderer</title>
    <style>
        #diagram {
            width: 100%;
            border: 1px solid #ddd;
            padding: 10px;
        }
    </style>
</head>
<body>

<div>
    <h1>Mermaid code</h1>
    <textarea id="mermaidCode" rows="10" cols="150" placeholder="Enter Mermaid code here">
</textarea>
<br />
<button id="renderButton">Render Diagram</button>
    <h1>Diagram</h1>
    <div id="diagram"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/mermaid@9.1.3/dist/mermaid.min.js"></script>
<script>
    // Initialize Mermaid
    mermaid.initialize({
        startOnLoad: false
    });

    // Get elements
    const mermaidCodeTextarea = document.getElementById('mermaidCode');
    const renderButton = document.getElementById('renderButton');
    const diagramDiv = document.getElementById('diagram');

    // Add event listener to the button
    renderButton.addEventListener('click', () => {
        const mermaidCode = mermaidCodeTextarea.value;
        diagramDiv.innerHTML = mermaidCode;
        mermaid.render('mermaid', mermaidCode, (svgCode) => {
            diagramDiv.innerHTML = svgCode;
        });
    });
</script>

</body>
</html>`
