### ISSUE TITLE
Create a table on the database to store configuration

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#121]
The idea is to have a table on the database to store the configurations.
This table will allow the change of a configuration without a new deployment.

Here is an example of a configuration table: 
`CREATE TABLE app_config (
    id SERIAL NOT NULL PRIMARY KEY,
    config_key VARCHAR(100) NOT NULL,
    config_value TEXT,
    config_type VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_config_key UNIQUE (config_key)
);

CREATE INDEX app_config_config_key_idx ON web_config(config_key);`

**Comment by jpb18** [comment]
We've talked on the daily and decided to add django, create the tables and enable the admin section.
