### ISSUE TITLE
Context definition

### ISSUE THREAD

**Issue by kenvontucky** [runtimerevolution/labs#18]
Set as context a code project, which can exist in a given path, to an LLM of your choice.

## Acceptance Criteria

- Validate the context was successfully created 
- environment variables with sensitive information must be avoided

**Comment by lmoreira-runtime** [comment]
1. List all the files within the project;
2. Ask the LLM to make an analysis about the content of the project and infere the associated technologies;
3. Load all files from revent-api project, except:
   - manage.py
   - .*
   - poetry.lock

**Comment by lmoreira-runtime** [comment]
Subject resolved in another issue
