### ISSUE TITLE
NLP Interface: Investigate acceptable minimum characters for NLP

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#39]
The idea is to test, investigate and determine the number of minimum characters of a request string that should pass through an NLP worker in order to generate a summary text to be used in an LLM prompt.

To do so, here are the possible tasks:

> Test the existing Spacy configuration with various prompts having different text lengths. 
- Record the results

>Test the different Spacy configurations with various prompts having different text lengths. 
- Record the results

> Investigate NLP technologies,  different than Spacy. 
- Record the results

> At the end, define the optimal, configuration for NLP:
- Library
- Minimum length for NLP summary

**Comment by lmoreira-runtime** [comment]
New wiki page with the results:

https://github.com/runtimerevolution/labs/wiki/NLP-Performance-Tests

**Comment by sIldefonsoRR** [comment]
Issue closed
