### ISSUE TITLE
LLM Interface: Include different LLMs in the flow

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#40]
The idea is to include different LLMs in the flow.
Here are some examples: 
- Falcon
- Gemini
- Claude
- etc.

> Experiment the same requests with different LLMs.
- Record the results
- Create more requests and run them in different LLMs
- Get patterns on the requests and responses in order to have an overview on the best LLM for each kind of cases

Store the findings in a table with scores.( ex: Falcon - python code - score 6 of 10 )

**Comment by ctmartinez1992** [comment]
This problem is solved but not necessarily functioning correctly.

The reason for this is because we currently hitting the max limit of tokens on the prompt.

To solve this issue, a RAG will be used. So, in essence, this issue is solved, just not working correctly.
