### ISSUE TITLE
LLM Interface: Use LLM to validate + clean generated output

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#41]
The idea is to have LLMs getting responses from code generation messages and:
> validate the output
- Check if the code is in-line with the request
- Check if the code is presentable and runnable

> clean the output
- Remove unnecessary texts from the code

Find and record the most frequent validations and cleanings, to be used in future actions.

**Comment by FilipaSdS** [comment]
Additionally, the modifying files section, needs to be discussed, we want the llm to indicates us the lines where to put or to give us the all file modified as a result
