### ISSUE TITLE
DOCUMENTATION: Create Flow diagram + Class diagram for code monkey

### ISSUE THREAD

**Issue by sIldefonsoRR** [runtimerevolution/labs#42]
The idea is to create the following diagrams:
- Flow Diagram
- Class Diagram

**Comment by sIldefonsoRR** [comment]
Here is a draft of the Flow Diagram.
`flowchart LR

    START --> 
    1[Get Issue]
    1 --> 2[Get Summary]
    2 --> 3[Call LLM]
    3 --> 4[Create File]
    4 --> 5[Create Branch]
    5 --> 6[Commit changes]
    6 --> 7[Create Pull Request]
    7 --> END`

![image](https://github.com/user-attachments/assets/582e7516-cad3-4211-9959-7582092bbcf5)

**Comment by FilipaSdS** [comment]
Updated:
flowchart LR
START -->  
1[Get Issue]
1 --> |Github Interface| 1
1 --> 2[Create Branch]
2 --> |Github Interface| 2
2 --> 3[Get Summary]
3 --> |NPL Interface| 3
3 --> 4[Call LLM]
4 --> |NLP Interface|4
4 --> 5[Response Analysis]
5 -->  |Response Parser|5
5--> 5.2[Create/Update files]
5.2 -->  |Response Parser|5.2
5.2 --> 6[Commit changes]
6 --> |Github Interface| 6
6 --> 7[Create Pull Request]
7 --> |Github Interface| 7
7 --> END
![Screenshot 2024-07-19 at 11 22 19](https://github.com/user-attachments/assets/7ace2c9a-28b2-4c20-abbb-231097b84c80)
