### ISSUE TITLE
Investigate Github App

### ISSUE THREAD

**Issue by kenvontucky** [runtimerevolution/labs#93]
Investigate all the necessary steps to create a Github app

https://docs.github.com/en/apps/creating-github-apps

* can we have a private app?
* where does the app live?
* how does it interact with our service?
    * does the existing api fulfil the job?

**Comment by ctmartinez1992** [comment]
> can we have a private app?

Yes, which can also be set to public.

> where does the app live?

still finding out...

> how does it interact with out service?

still finding out...

> does the existing api fulfill the job?

still finding out...
